Initial Point Model created
VadMack/Travel-app pull request #12
Opened 2022-04-03 16:52 UTC by galex2122

2022-04-04 17:07 UTC, galex2122 commented on src/main/java/com/vas/travelapp/repository/model/AddressModel.java
> +    private String StreetName;
Рукожоп

2022-04-04 17:19 UTC, galex2122 commented
перенести модельки в домаин

2022-04-08 19:44 UTC, ssstoyanov requested changes

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/PointRepository.java
> +@Repository
необязательна если наследуешь MongoRepository

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/AddressModel.java
> +@EqualsAndHashCode
стоит писать явно, ломбок не всегда генерирует подходящие методы

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/AddressModel.java
> +    private String StreetName;
с маленькой буквы

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/AddressModel.java
> +    private Double latitude;
нема либ которые умеют в гео?

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/OperationHoursModel.java
> +@Document("opHours")
@Document("opHours")
@TypeAlias("opHour")

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/AddressModel.java
> +@Document("addresses")
@Document("addresses")
@TypeAlias("address")

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/PointModel.java
> +@EqualsAndHashCode
тоже самое

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/common/PriceLevel.java
> +    VERY_EXPENSIVE;
PREMIUM?

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/common/PointType.java
> +    ;
RESTARAUNT
MUSEUM
GALLERY
EVENT

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/PointModel.java
> +    private List<OperationHoursModel> workSchedule;
@DBRef?

2022-04-08 19:44 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/PointModel.java
> +    private AddressModel address;
@DBRef?

2022-04-08 19:45 UTC, ssstoyanov commented
> перенести модельки в домейн

100%

domain/address

2022-04-08 19:45 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/common/PriceLevel.java
> +public enum PriceLevel {
PriceType

2022-04-08 19:46 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/AddressModel.java
> +public class AddressModel {
Address

2022-04-08 19:46 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/OperationHoursModel.java
> +public class OperationHoursModel {
OperationHours

2022-04-08 19:46 UTC, ssstoyanov commented on src/main/java/com/vas/travelapp/repository/model/PointModel.java
> +public class PointModel {
Point

2022-04-17 14:26 UTC, merged